$font = Open Sans
$wallpaper = ~/.local/share/wallpapers/current.jpg

general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

animations {
    enabled = true
    bezier = easeOut, 0.22, 1, 0.36, 1
    animation = fadeIn, 1, 4, easeOut
    animation = fadeOut, 1, 4, easeOut
    animation = inputFieldDots, 1, 2, easeOut
}

background {
    monitor =
    path = $wallpaper
    blur_passes = 1
    blur_size = 3
    noise = 0.0117
    contrast = 1.0
    brightness = 0.72
    vibrancy = 0.12
    vibrancy_darkness = 0.15
    color = rgba(21222cff)
}

label {
    monitor =
    text = $TIME
    color = rgba(ffffffff)
    font_size = 86
    font_family = $font
    position = 0, 125
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgba(bbbbbbff)
    font_size = 18
    font_family = $font
    position = 0, 48
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 58
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.20
    dots_center = true
    outer_color = rgba(343746ff)
    inner_color = rgba(222222dd)
    font_color = rgba(ffffffff)
    fail_color = rgba(f85149ff)
    check_color = rgba(b7cef1ff)
    capslock_color = rgba(d29922ff)
    rounding = 20
    font_family = $font
    placeholder_text = Password
    fail_text = Authentication failed
    fade_on_empty = false
    position = 0, -78
    halign = center
    valign = center
}
